#ifndef FWDEMO_DK_PLATFORM_OS_OPTIONS_HPP_
#define FWDEMO_DK_PLATFORM_OS_OPTIONS_HPP_

#define OS_THREAD_POOL_SIZE 4
#define OS_MUTEX_POOL_SIZE 4
#define OS_SEMAPHORE_POOL_SIZE 4
#define OS_EVENT_FLAG_POOL_SIZE 4

#endif // FWDEMO_DK_PLATFORM_OS_OPTIONS_HPP_
